### ISSUE TITLE
Dataset cannot be processed with newest lingpy

### ISSUE THREAD

**Issue by xrotwang** [lexibank/zgraggenmadang#3]
This is what I get:
```python
ValueError: [!] your sequence contains only unknown characters
```
(after un-masking the error in `lingpy/basic/parser.py` line 365).

**Comment by LinguList** [comment]
Yes, this is a new and wanted feature. But I wonder why it woudl occur here? Don't we use orthoprofiles? Why do we use tokens2class as a function?
